name: Deploy GitBook to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy GitBook
        uses: zanderzhao/gitbook-action@v1.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source_dir: .                # <-- корень репозитория, где лежат ваши .md и папки
          publish_branch: gh-pages
          publish_dir: ./_book
